name: CI - Tests automatiques

on:
  push:
    branches: [ "dev" ]   # ou main/master selon ton projet
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installer dépendances backend
        run: npm install
        working-directory: backend

      - name: Lancer les tests backend
        run: npm test
        working-directory: backend
